joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 60

# real time controllers
arm_flex_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_flex_joint
  pid: { p: 2000, i: 100, d: 50 }

arm_lift_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_lift_joint
  pid: { p: 2000, i: 100, d: 50 }

arm_roll_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_roll_joint
  pid: { p: 2000, i: 100, d: 50 }

head_pan_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: head_pan_joint
  pid: { p: 2000, i: 100, d: 50 }

head_tilt_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: head_tilt_joint
  pid: { p: 2000, i: 100, d: 50 }

wrist_flex_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: wrist_flex_joint
  pid: { p: 2000, i: 100, d: 50 }

wrist_roll_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: wrist_roll_joint
  pid: { p: 2000, i: 100, d: 50 }

hand_motor_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: hand_motor_joint
  pid: { p: 2000, i: 100, d: 50 }

hand_l_spring_proximal_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: hand_l_spring_proximal_joint
  pid: { p: 2000, i: 100, d: 50 }

hand_r_spring_proximal_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: hand_r_spring_proximal_joint
  pid: { p: 2000, i: 100, d: 50 }


# follow joint trajectory controller
arm_trajectory_controller:
  type: effort_controllers/JointTrajectoryController  
  joints:
    - arm_flex_joint
    - arm_lift_joint
    - arm_roll_joint
    - wrist_flex_joint
    - wrist_roll_joint
  gains:
    arm_flex_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    arm_lift_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    arm_roll_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    wrist_flex_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    wrist_roll_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
  constraints:
    stopped_velocity_tolerance: 0

head_trajectory_controller:
  type: effort_controllers/JointTrajectoryController  
  joints:
    - head_pan_joint
    - head_tilt_joint
  gains:
    head_pan_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
    head_tilt_joint: {p: 2000, i: 100, d: 50, i_clamp: 10}
  constraints:
    stopped_velocity_tolerance: 0