use_map_topic: true
odom_model_type: omni-corrected

base_frame_id: Armar6
odom_frame_id: odom
global_frame_id: map

gui_publish_rate: 10.0 # Publish scans from best pose at a max of 10 Hz

transform_tolerance: 0.1

min_particles: 500
max_particles: 5000

kld_err: 0.05
kld_z: 0.95

odom_alpha1: 0.005 # trans noise by rot movement
odom_alpha2: 0.5 # rot noise trans movement
odom_alpha3: 0.3 # trans noise by trans movement
odom_alpha4: 0.005 # rot noise by rot movement
odom_alpha5: 0.2 # translation related noise for omni

update_min_d: 0.01
update_min_a: 0.01
resample_interval: 1

laser_max_beams: 50
laser_max_range: 12.0

laser_z_hit: 0.975
laser_z_short: 0.1
laser_z_max: 0.05
laser_z_rand: 0.05
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
laser_model_type: likelihood_field
laser_likelihood_max_dist: 10.0
laser_min_range: 0.1

recovery_alpha_slow: 0.0
recovery_alpha_fast: 0.0