joint_state_controller:
  type:         joint_state_controller/JointStateController
  publish_rate: 1000

joint_trajectory_controller: 
  type: effort_controllers/JointTrajectoryController  
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  gains:
    panda_joint1: {p: 2000, i: 100, d: 50}
    panda_joint2: {p: 2000, i: 100, d: 50}
    panda_joint3: {p: 2000, i: 100, d: 50}
    panda_joint4: {p: 2000, i: 100, d: 50}
    panda_joint5: {p: 2000, i: 100, d: 50}
    panda_joint6: {p: 2000, i: 100, d: 50}
    panda_joint7: {p: 2000, i: 100, d: 50}

panda_joint1_position_controller:
  type:         effort_controllers/JointPositionController
  joint:        panda_joint1
  pid:          {p: 2000, i: 100, d: 50}

panda_joint2_position_controller:
  type:         effort_controllers/JointPositionController
  joint:        panda_joint2
  pid:          {p: 2000, i: 100, d: 50}

panda_joint3_position_controller:
  type:         effort_controllers/JointPositionController
  joint:        panda_joint3
  pid:          {p: 2000, i: 100, d: 50}

panda_joint4_position_controller:
  type:         effort_controllers/JointPositionController
  joint:        panda_joint4
  pid:          {p: 2000, i: 100, d: 50}

panda_joint5_position_controller:
  type:         effort_controllers/JointPositionController
  joint:        panda_joint5
  pid:          {p: 2000, i: 100, d: 50}

panda_joint6_position_controller:
  type:         effort_controllers/JointPositionController
  joint:        panda_joint6
  pid:          {p: 2000, i: 100, d: 50}

panda_joint7_position_controller:
  type:         effort_controllers/JointPositionController
  joint:        panda_joint7
  pid:          {p: 2000, i: 100, d: 50}

panda_joint1_velocity_controller:
  type:         effort_controllers/JointVelocityController
  joint:        panda_joint1
  pid:          {p: 100, i: 1, d: 0.1}

panda_joint2_velocity_controller:
  type:         effort_controllers/JointVelocityController
  joint:        panda_joint2
  pid:          {p: 100, i: 1, d: 0.1}

panda_joint3_velocity_controller:
  type:         effort_controllers/JointVelocityController
  joint:        panda_joint3
  pid:          {p: 100, i: 1, d: 0.1}

panda_joint4_velocity_controller:
  type:         effort_controllers/JointVelocityController
  joint:        panda_joint4
  pid:          {p: 100, i: 1, d: 0.1}

panda_joint5_velocity_controller:
  type:         effort_controllers/JointVelocityController
  joint:        panda_joint5
  pid:          {p: 100, i: 1, d: 0.1}

panda_joint6_velocity_controller:
  type:         effort_controllers/JointVelocityController
  joint:        panda_joint6
  pid:          {p: 100, i: 1, d: 0.1}

panda_joint7_velocity_controller:
  type:         effort_controllers/JointVelocityController
  joint:        panda_joint7
  pid:          {p: 100, i: 1, d: 0.1}