
global_frame: map
robot_base_frame: base_footprint

update_frequency: 5.0
publish_frequency: 5.0

obstacle_range: 5
raytrace_range: 6
footprint: [[-0.6, -0.4], [-0.6, 0.4], [0.6, 0.4], [0.6, -0.4]]
#robot_radius: ir_of_robot

inflation:
  inflation_radius: 0.5

obstacles_laser:
  observation_sources: laser_scan_sensor_front laser_scan_sensor_back
  laser_scan_sensor_front: {sensor_frame: laser_reference_front, data_type: LaserScan, topic: hokuyo_front/most_intense, marking: true, clearing: true}
  laser_scan_sensor_back: {sensor_frame: laser_reference_back, data_type: LaserScan, topic: hokuyo_back/most_intense, marking: true, clearing: true}