joints:
  - bl_caster_rotation_joint
  - bl_caster_wheel_joint
  - br_caster_rotation_joint
  - br_caster_wheel_joint
  - fl_caster_rotation_joint
  - fl_caster_wheel_joint
  - fr_caster_rotation_joint
  - fr_caster_wheel_joint
  - left_wheel_joint
  - right_wheel_joint
  - pan_motor
  - lift_arm_lower
  - lift_motor_joint
  - lift_arm_upper
  - carriage
  - castor_rigit_left_wheel
  - castor_rigit_right_wheel
  - castor_swivel_left_fork
  - castor_swivel_right_fork
  - castor_swivel_left_wheel
  - castor_swivel_right_wheel

odom_x_joint: odom_x_joint
odom_y_joint: odom_y_joint
odom_z_joint: odom_z_joint