# This controller publishes the joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 60

torso_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints:
    - torso_lift_joint
  gains:
    torso_lift_joint:    { p: 2000, i: 100, d: 50 }


r_arm_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints:
    - r_shoulder_pan_joint
    - r_shoulder_lift_joint
    - r_upper_arm_roll_joint
    - r_elbow_flex_joint
    - r_forearm_roll_joint
    - r_wrist_flex_joint
    - r_wrist_roll_joint
  gains:
    r_shoulder_pan_joint:    { p: 2000, i: 100, d: 50 }
    r_shoulder_lift_joint:   { p: 2000, i: 100, d: 50 }
    r_upper_arm_roll_joint:  { p: 2000, i: 100, d: 50 }
    r_elbow_flex_joint:      { p: 2000, i: 100, d: 50 }
    r_forearm_roll_joint:    { p: 2000, i: 100, d: 50 }
    r_wrist_flex_joint:      { p: 2000, i: 100, d: 50 }
    r_wrist_roll_joint:      { p: 2000, i: 100, d: 50 }

l_arm_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints:
    - l_shoulder_pan_joint
    - l_shoulder_lift_joint
    - l_upper_arm_roll_joint
    - l_elbow_flex_joint
    - l_forearm_roll_joint
    - l_wrist_flex_joint
    - l_wrist_roll_joint
  gains:
    l_shoulder_pan_joint:    { p: 2000, i: 100, d: 50 }
    l_shoulder_lift_joint:   { p: 2000, i: 100, d: 50 }
    l_upper_arm_roll_joint:  { p: 2000, i: 100, d: 50 }
    l_elbow_flex_joint:      { p: 2000, i: 100, d: 50 }
    l_forearm_roll_joint:    { p: 2000, i: 100, d: 50 }
    l_wrist_flex_joint:      { p: 2000, i: 100, d: 50 }
    l_wrist_roll_joint:      { p: 2000, i: 100, d: 50 }

l_gripper_controller:
  type: effort_controllers/JointEffortController
  joint: l_gripper_l_finger_joint

r_gripper_controller:
  type: effort_controllers/JointEffortController
  joint: r_gripper_l_finger_joint