global_frame: map
robot_base_frame: base_footprint

update_frequency: 5.0
publish_frequency: 5.0

obstacle_range: 5
raytrace_range: 6
footprint: [[-0.6, -0.4], [-0.6, 0.4], [0.6, 0.4], [0.6, -0.4]]

inflation:
  inflation_radius: 0.4

obstacles_laser:
  observation_sources: base_scan
  base_scan:
    {
      sensor_frame: base_laser_link,
      data_type: LaserScan,
      topic: tiago_dual/base_laser,
      marking: true,
      clearing: true,
    }
