local_costmap:
  rolling_window: true
  width: 4.0
  height: 4.0
  resolution: 0.02

  plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}