robots: [hsrb4s]

pose_init: 
  hsrb4s: [1.3, 2.5, 0.0, 0.0, 0.0, 0.0]

max_time_step: 0.005

add_odom_joints: true

pub_tf:
  world_bodies_rate: 0.0

pub_object_state_array:
  world_bodies_rate:  60.0

pub_joint_states:
  world_bodies_rate:  60.0

pub_base_pose_rate: 60.0

spawn_and_destroy_objects_rate: 60.0

root_frame_id: odom