add_odom_joints: true

pub_object_marker_array_rate: 60.0

pub_object_tf_rate: 60.0

pub_object_state_array_rate: 60.0

pub_world_joint_state_rate: 0.0

pub_base_pose_rate: 60.0

spawn_and_destroy_objects_rate: 600.0

root_frame_id: map