joint_names:
  - panda_1_joint1
  - panda_1_joint2
  - panda_1_joint3
  - panda_1_joint4
  - panda_1_joint5
  - panda_1_joint6
  - panda_1_joint7
  - panda_2_joint1
  - panda_2_joint2
  - panda_2_joint3
  - panda_2_joint4
  - panda_2_joint5
  - panda_2_joint6
  - panda_2_joint7
  - panda_1_finger_joint1
  - panda_1_finger_joint2
  - panda_2_finger_joint1
  - panda_2_finger_joint2

init_positions:
  panda_1_joint1: 0
  panda_1_joint2: 0
  panda_1_joint3: 0
  panda_1_joint4: 0
  panda_1_joint5: 0
  panda_1_joint6: 0
  panda_1_joint7: 0
  panda_2_joint1: 0
  panda_2_joint2: 0
  panda_2_joint3: 0
  panda_2_joint4: 0
  panda_2_joint5: 0
  panda_2_joint6: 0
  panda_2_joint7: 0
  panda_1_finger_joint1: 0
  panda_1_finger_joint2: 0
  panda_2_finger_joint1: 0
  panda_2_finger_joint2: 0