joint_inits:
  panda_joint1: 0
  panda_joint2: 0
  panda_joint3: 0
  panda_joint4: 0
  panda_joint5: 0
  panda_joint6: 0
  panda_joint7: 0

use_odom_joints: false

pub_object_marker_array: true

pub_object_tf: true

pub_object_state_array: true

root_frame_id: map