joint_inits:
  panda_joint1: 0
  panda_joint2: 0
  panda_joint3: 0
  panda_joint4: 0
  panda_joint5: 0
  panda_joint6: 0
  panda_joint7: 0

add_odom_joints: false

pub_object_marker_array_rate: 0.0

pub_object_tf_rate: 0.0

pub_object_state_array_rate: 0.0

pub_world_joint_states_rate: 0.0

pub_base_pose_rate: 60.0

spawn_and_destroy_objects_rate: 0.0

root_frame_id: map