joint_state_controller:
  type:         joint_state_controller/JointStateController
  publish_rate: 1000

shoulder_pan_joint_position_controller:
  type:         effort_controllers/JointPositionController
  joint:        shoulder_pan_joint
  pid:          {p: 2000, i: 100, d: 50}

shoulder_lift_joint_position_controller:
  type:         effort_controllers/JointPositionController
  joint:        shoulder_lift_joint
  pid:          {p: 2000, i: 100, d: 50}

elbow_joint_position_controller:
  type:         effort_controllers/JointPositionController
  joint:        elbow_joint
  pid:          {p: 2000, i: 100, d: 50}

wrist_1_joint_position_controller:
  type:         effort_controllers/JointPositionController
  joint:        wrist_1_joint
  pid:          {p: 2000, i: 100, d: 50}

wrist_2_joint_position_controller:
  type:         effort_controllers/JointPositionController
  joint:        wrist_2_joint
  pid:          {p: 2000, i: 100, d: 50}

wrist_3_joint_position_controller:
  type:         effort_controllers/JointPositionController
  joint:        wrist_3_joint
  pid:          {p: 2000, i: 100, d: 50}

shoulder_pan_joint_velocity_controller:
  type:         effort_controllers/JointVelocityController
  joint:        shoulder_pan_joint
  pid:          {p: 100, i: 1, d: 0.1}

shoulder_lift_joint_velocity_controller:
  type:         effort_controllers/JointVelocityController
  joint:        shoulder_lift_joint
  pid:          {p: 100, i: 1, d: 0.1}

elbow_joint_velocity_controller:
  type:         effort_controllers/JointVelocityController
  joint:        elbow_joint
  pid:          {p: 100, i: 1, d: 0.1}

wrist_1_joint_velocity_controller:
  type:         effort_controllers/JointVelocityController
  joint:        wrist_1_joint
  pid:          {p: 100, i: 1, d: 0.1}

wrist_2_joint_velocity_controller:
  type:         effort_controllers/JointVelocityController
  joint:        wrist_2_joint
  pid:          {p: 100, i: 1, d: 0.1}

wrist_3_joint_velocity_controller:
  type:         effort_controllers/JointVelocityController
  joint:        wrist_3_joint
  pid:          {p: 100, i: 1, d: 0.1}
   