joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 60

torso_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - TorsoJoint
  gains:
    TorsoJoint: &pid_gains {p: 2000, i: 100, d: 50}

head_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - Neck_1_Yaw
    - Neck_2_Pitch
  gains:
    Neck_1_Yaw: *pid_gains
    Neck_2_Pitch: *pid_gains

arm_left_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - ArmL1_Cla1
    - ArmL2_Sho1
    - ArmL3_Sho2
    - ArmL4_Sho3
    - ArmL5_Elb1
    - ArmL6_Elb2
    - ArmL7_Wri1
    - ArmL8_Wri2 
  gains:
    ArmL1_Cla1: *pid_gains
    ArmL2_Sho1: *pid_gains
    ArmL3_Sho2: *pid_gains
    ArmL4_Sho3: *pid_gains
    ArmL5_Elb1: *pid_gains
    ArmL6_Elb2: *pid_gains
    ArmL7_Wri1: *pid_gains
    ArmL8_Wri2: *pid_gains

arm_right_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - ArmR1_Cla1
    - ArmR2_Sho1
    - ArmR3_Sho2
    - ArmR4_Sho3
    - ArmR5_Elb1
    - ArmR6_Elb2
    - ArmR7_Wri1
    - ArmR8_Wri2 
  gains:
    ArmR1_Cla1: *pid_gains
    ArmR2_Sho1: *pid_gains
    ArmR3_Sho2: *pid_gains
    ArmR4_Sho3: *pid_gains
    ArmR5_Elb1: *pid_gains
    ArmR6_Elb2: *pid_gains
    ArmR7_Wri1: *pid_gains
    ArmR8_Wri2: *pid_gains

Index_L_1_Joint_controller:
  type: effort_controllers/GripperActionController
  joint: Index_L_1_Joint
  gains:
    Index_L_1_Joint: { p: 2000, i: 10, d: 50 }

Index_L_2_Joint_controller:
  type: effort_controllers/GripperActionController
  joint: Index_L_2_Joint
  gains:
    Index_L_2_Joint: { p: 2000, i: 10, d: 50 }

Index_L_3_Joint_controller:
  type: effort_controllers/GripperActionController
  joint: Index_L_3_Joint
  gains:
    Index_L_3_Joint: { p: 2000, i: 10, d: 50 }

Index_R_1_Joint_controller:
  type: effort_controllers/GripperActionController
  joint: Index_R_1_Joint
  gains:
    Index_R_1_Joint: { p: 2000, i: 10, d: 50 }

Index_R_2_Joint_controller:
  type: effort_controllers/GripperActionController
  joint: Index_R_2_Joint
  gains:
    Index_R_2_Joint: { p: 2000, i: 10, d: 50 }

Index_R_3_Joint_controller:
  type: effort_controllers/GripperActionController
  joint: Index_R_3_Joint
  gains:
    Index_R_3_Joint: { p: 2000, i: 10, d: 50 }

Middle_L_1_Joint_controller:
  type: effort_controllers/GripperActionController
  joint: Middle_L_1_Joint
  gains:
    Middle_L_1_Joint: { p: 2000, i: 10, d: 50 }

Middle_L_2_Joint_controller:
  type: effort_controllers/GripperActionController
  joint: Middle_L_2_Joint
  gains:
    Middle_L_2_Joint: { p: 2000, i: 10, d: 50 }

Middle_L_3_Joint_controller:
  type: effort_controllers/GripperActionController
  joint: Middle_L_3_Joint
  gains:
    Middle_L_3_Joint: { p: 2000, i: 10, d: 50 }

Middle_R_1_Joint_controller:
  type: effort_controllers/GripperActionController
  joint: Middle_R_1_Joint
  gains:
    Middle_R_1_Joint: { p: 2000, i: 10, d: 50 }

Middle_R_2_Joint_controller:
  type: effort_controllers/GripperActionController
  joint: Middle_R_2_Joint
  gains:
    Middle_R_2_Joint: { p: 2000, i: 10, d: 50 }

Middle_R_3_Joint_controller:
  type: effort_controllers/GripperActionController
  joint: Middle_R_3_Joint
  gains:
    Middle_R_3_Joint: { p: 2000, i: 10, d: 50 }

Pinky_L_1_Joint_controller:
  type: effort_controllers/GripperActionController
  joint: Pinky_L_1_Joint
  gains:
    Pinky_L_1_Joint: { p: 2000, i: 10, d: 50 }

Pinky_L_2_Joint_controller:
  type: effort_controllers/GripperActionController
  joint: Pinky_L_2_Joint
  gains:
    Pinky_L_2_Joint: { p: 2000, i: 10, d: 50 }

Pinky_L_3_Joint_controller:
  type: effort_controllers/GripperActionController
  joint: Pinky_L_3_Joint
  gains:
    Pinky_L_3_Joint: { p: 2000, i: 10, d: 50 }

Pinky_R_1_Joint_controller:
  type: effort_controllers/GripperActionController
  joint: Pinky_R_1_Joint
  gains:
    Pinky_R_1_Joint: { p: 2000, i: 10, d: 50 }

Pinky_R_2_Joint_controller:
  type: effort_controllers/GripperActionController
  joint: Pinky_R_2_Joint
  gains:
    Pinky_R_2_Joint: { p: 2000, i: 10, d: 50 }

Pinky_R_3_Joint_controller:
  type: effort_controllers/GripperActionController
  joint: Pinky_R_3_Joint
  gains:
    Pinky_R_3_Joint: { p: 2000, i: 10, d: 50 }

Ring_L_1_Joint_controller:
  type: effort_controllers/GripperActionController
  joint: Ring_L_1_Joint
  gains:
    Ring_L_1_Joint: { p: 2000, i: 10, d: 50 }

Ring_L_2_Joint_controller:
  type: effort_controllers/GripperActionController
  joint: Ring_L_2_Joint
  gains:
    Ring_L_2_Joint: { p: 2000, i: 10, d: 50 }

Ring_L_3_Joint_controller:
  type: effort_controllers/GripperActionController
  joint: Ring_L_3_Joint
  gains:
    Ring_L_3_Joint: { p: 2000, i: 10, d: 50 }

Ring_R_1_Joint_controller:
  type: effort_controllers/GripperActionController
  joint: Ring_R_1_Joint
  gains:
    Ring_R_1_Joint: { p: 2000, i: 10, d: 50 }

Ring_R_2_Joint_controller:
  type: effort_controllers/GripperActionController
  joint: Ring_R_2_Joint
  gains:
    Ring_R_2_Joint: { p: 2000, i: 10, d: 50 }

Ring_R_3_Joint_controller:
  type: effort_controllers/GripperActionController
  joint: Ring_R_3_Joint
  gains:
    Ring_R_3_Joint: { p: 2000, i: 10, d: 50 }

Thumb_L_1_Joint_controller:
  type: effort_controllers/GripperActionController
  joint: Thumb_L_1_Joint
  gains:
    Thumb_L_1_Joint: { p: 2000, i: 10, d: 50 }

Thumb_L_2_Joint_controller:
  type: effort_controllers/GripperActionController
  joint: Thumb_L_2_Joint
  gains:
    Thumb_L_2_Joint: { p: 2000, i: 10, d: 50 }

Thumb_R_1_Joint_controller:
  type: effort_controllers/GripperActionController
  joint: Thumb_R_1_Joint
  gains:
    Thumb_R_1_Joint: { p: 2000, i: 10, d: 50 }

Thumb_R_2_Joint_controller:
  type: effort_controllers/GripperActionController
  joint: Thumb_R_2_Joint
  gains:
    Thumb_R_2_Joint: { p: 2000, i: 10, d: 50 }

left_hand_fingers_controller:
  type: effort_controllers/GripperActionController
  joint: LeftHandFingers
  gains:
    LeftHandFingers: { p: 2000, i: 10, d: 50 }

left_hand_thumb_controller:
  type: effort_controllers/GripperActionController
  joint: LeftHandThumb
  gains:
    LeftHandThumb: { p: 2000, i: 10, d: 50 }

right_hand_fingers_controller:
  type: effort_controllers/GripperActionController
  joint: RightHandFingers
  gains:
    RightHandFingers: { p: 2000, i: 10, d: 50 }

right_hand_thumb_controller:
  type: effort_controllers/GripperActionController
  joint: RightHandThumb
  gains:
    RightHandThumb: { p: 2000, i: 10, d: 50 }