joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 60

torso_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints:
    - torso_lift_joint
  gains:
    torso_lift_joint: &pid_gains {p: 2000, i: 100, d: 50}
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 5.0 # FIXME: See #8429
    torso_lift_joint:
      goal: 0.001

head_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints:
    - head_1_joint
    - head_2_joint
  gains:
    head_1_joint: *pid_gains
    head_2_joint: *pid_gains
  constraints:
    goal_time: 2.0
    stopped_velocity_tolerance: 5.0
    head_1_joint:
      goal: 0.02
    head_2_joint:
      goal: 0.02

arm_left_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints:
    - arm_left_1_joint
    - arm_left_2_joint
    - arm_left_3_joint
    - arm_left_4_joint
    - arm_left_5_joint
    - arm_left_6_joint
    - arm_left_7_joint
  gains:
    arm_left_1_joint: *pid_gains
    arm_left_2_joint: *pid_gains
    arm_left_3_joint: *pid_gains
    arm_left_4_joint: *pid_gains
    arm_left_5_joint: *pid_gains
    arm_left_6_joint: *pid_gains
    arm_left_7_joint: *pid_gains
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 5.0
    arm_left_1_joint:
      goal: 0.02
    arm_left_2_joint:
      goal: 0.02
    arm_left_3_joint:
      goal: 0.02
    arm_left_4_joint:
      goal: 0.02
    arm_left_5_joint:
      goal: 0.02
    arm_left_6_joint:
      goal: 0.02
    arm_left_7_joint:
      goal: 0.02

arm_right_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints:
    - arm_right_1_joint
    - arm_right_2_joint
    - arm_right_3_joint
    - arm_right_4_joint
    - arm_right_5_joint
    - arm_right_6_joint
    - arm_right_7_joint
  gains:
    arm_right_1_joint: *pid_gains
    arm_right_2_joint: *pid_gains
    arm_right_3_joint: *pid_gains
    arm_right_4_joint: *pid_gains
    arm_right_5_joint: *pid_gains
    arm_right_6_joint: *pid_gains
    arm_right_7_joint: *pid_gains
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 5.0
    arm_right_1_joint:
      goal: 0.02
    arm_right_2_joint:
      goal: 0.02
    arm_right_3_joint:
      goal: 0.02
    arm_right_4_joint:
      goal: 0.02
    arm_right_5_joint:
      goal: 0.02
    arm_right_6_joint:
      goal: 0.02
    arm_right_7_joint:
      goal: 0.02

gripper_left_left_finger:
  type: effort_controllers/GripperActionController
  joint: gripper_left_left_finger_joint
  gains:
    gripper_left_left_finger_joint: *pid_gains

gripper_left_right_finger:
  type: effort_controllers/GripperActionController
  joint: gripper_left_right_finger_joint
  gains:
    gripper_left_right_finger_joint: *pid_gains

gripper_right_left_finger:
  type: effort_controllers/GripperActionController
  joint: gripper_right_left_finger_joint
  gains:
    gripper_right_left_finger_joint: *pid_gains

gripper_right_right_finger:
  type: effort_controllers/GripperActionController
  joint: gripper_right_right_finger_joint
  gains:
    gripper_right_right_finger_joint: *pid_gains

# gripper_left_left_finger_effort_controller:
#   type: effort_controllers/JointEffortController
#   joint: gripper_left_left_finger_joint
# gripper_left_right_finger_effort_controller:
#   type: effort_controllers/JointEffortController
#   joint: gripper_left_right_finger_joint
# gripper_right_left_finger_effort_controller:
#   type: effort_controllers/JointEffortController
#   joint: gripper_right_left_finger_joint
# gripper_right_right_finger_effort_controller:
#   type: effort_controllers/JointEffortController
#   joint: gripper_right_right_finger_joint