joint_inits:
  shoulder_pan_joint: 1
  shoulder_lift_joint: -1
  elbow_joint: -1
  wrist_1_joint: -1
  wrist_2_joint: 1
  wrist_3_joint: 1

use_odom_joints: false

pub_object_marker_array: true

pub_object_tf: true

pub_object_state_array: true

root_frame_id: map