global_frame: map
robot_base_frame: ridgeback_panda/base_link

update_frequency: 5.0
publish_frequency: 5.0

obstacle_range: 5
raytrace_range: 6
footprint: [[-0.6, -0.4], [-0.6, 0.4], [0.6, 0.4], [0.6, -0.4]]

inflation:
  inflation_radius: 1.0

obstacles_laser:
  observation_sources: laser_front laser_rear
  laser_front:
    {
      sensor_frame: ridgeback_panda/front_laser,
      data_type: LaserScan,
      topic: ridgeback_panda/laser_front,
      marking: true,
      clearing: true,
    }
  laser_rear:
    {
      sensor_frame: ridgeback_panda/rear_laser,
      data_type: LaserScan,
      topic: ridgeback_panda/laser_rear,
      marking: true,
      clearing: true,
    }
