robots:
  - ridgeback_panda
  - mir_system

pose_init:
  ridgeback_panda: [0, 1, 0, 0, 0, 0]
  mir_system: [0, 0, 0, 0, 0, 0]

max_time_step: 0.01

add_odom_joints:
  lin_odom_x_joint: true
  lin_odom_y_joint: true
  lin_odom_z_joint: true
  ang_odom_x_joint: false
  ang_odom_y_joint: false
  ang_odom_z_joint: true

pub_tf:
  world_bodies_rate: 10.0
  spawned_object_bodies_rate: 0.0

pub_object_state_array:
  world_bodies_rate:  10.0
  spawned_object_bodies_rate: 0.0

pub_joint_states:
  world_bodies_rate:  0.0
  spawned_object_bodies_rate: 0.0

pub_base_pose_rate: 10.0

spawn_and_destroy_objects_rate: 60.0

spawn_object_count_per_cycle: 20

root_frame_id: odom
