robots:
  - ridgeback_panda
  - mir_system

pose_init:
  ridgeback_panda: [0, 1, 0, 0, 0, 0]
  mir_system: [0, 0, 0, 0, 0, 0]

joint_ignores:
  # mir
  - left_wheel_joint
  - right_wheel_joint
  - fl_caster_rotation_joint
  - fl_caster_wheel_link
  - fr_caster_rotation_joint
  - fr_caster_wheel_joint
  - bl_caster_rotation_joint
  - bl_caster_wheel_link
  - br_caster_rotation_joint
  - br_caster_wheel_joint
  # hook + trailer
  - carriage
  - lift_arm_lower
  - lift_arm_upper
  - lift_motor_joint
  - pan_motor
  - castor_rigit_left_wheel
  - castor_rigit_right_wheel
  - castor_swivel_left_fork
  - castor_swivel_left_wheel
  - castor_swivel_right_fork
  - castor_swivel_right_wheel

  # ridgeback
  - front_rocker
  - front_left_wheel
  - front_right_wheel
  - rear_left_wheel
  - rear_right_wheel

max_time_step: 0.01

add_odom_joints:
  lin_odom_x_joint: true
  lin_odom_y_joint: true
  lin_odom_z_joint: true
  ang_odom_x_joint: false
  ang_odom_y_joint: false
  ang_odom_z_joint: true

pub_tf:
  world_bodies_rate: 10.0
  spawned_object_bodies_rate: 0.0

pub_object_state_array:
  world_bodies_rate:  10.0
  spawned_object_bodies_rate: 0.0

pub_joint_states:
  world_bodies_rate:  0.0
  spawned_object_bodies_rate: 0.0

pub_base_pose_rate: 10.0

spawn_and_destroy_objects_rate: 60.0

spawn_object_count_per_cycle: 20

root_frame_id: odom
