robots:
  - ridgeback_panda
  - mir_system

joint_ignores:
  # mir
  - left_wheel_joint
  - right_wheel_joint
  - fl_caster_rotation_joint
  - fl_caster_wheel_link
  - fr_caster_rotation_joint
  - fr_caster_wheel_joint
  - bl_caster_rotation_joint
  - bl_caster_wheel_link
  - br_caster_rotation_joint
  - br_caster_wheel_joint
  # hook + trailer
  - carriage
  - lift_arm_lower
  - lift_arm_upper
  - lift_motor_joint
  - pan_motor
  - castor_rigit_left_wheel
  - castor_rigit_right_wheel
  - castor_swivel_left_fork
  - castor_swivel_left_wheel
  - castor_swivel_right_fork
  - castor_swivel_right_wheel

  # ridgeback
  - front_rocker
  - front_left_wheel
  - front_right_wheel
  - rear_left_wheel
  - rear_right_wheel

max_time_step: 0.02

add_odom_joints: true

pub_object_marker_array_rate: 0.0

pub_object_tf_rate: 10.0

pub_object_state_array_rate: 60.0

pub_world_joint_state_rate: 0.0

pub_base_pose_rate: 60.0

spawn_and_destroy_objects_rate: 600.0

spawn_object_count_per_cycle: 20

root_frame_id: odom
