joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 60

joint_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - iiwa_joint_1
    - iiwa_joint_2
    - iiwa_joint_3
    - iiwa_joint_4
    - iiwa_joint_5
    - iiwa_joint_6
    - iiwa_joint_7
  gains:
    iiwa_joint_1: { p: 2000, i: 100, d: 50 }
    iiwa_joint_2: { p: 2000, i: 100, d: 50 }
    iiwa_joint_3: { p: 2000, i: 100, d: 50 }
    iiwa_joint_4: { p: 2000, i: 100, d: 50 }
    iiwa_joint_5: { p: 2000, i: 100, d: 50 }
    iiwa_joint_6: { p: 2000, i: 100, d: 50 }
    iiwa_joint_7: { p: 2000, i: 100, d: 50 }
